version: 2

sources:
  - name: sources
    description: Data sources
    schema: sources
    config:
      enabled: true
    tables:
      - name: transactions
        columns:
          - name: transaction_id
            description: Unique transaction ID
            tests:
              - unique
              - not_null
          - name: booking
            description: Date when the transaction was booked
          - name: value_date
            description: Date when the transaction was executed
          - name: client_recipient
            description: Client / Recipient
          - name: booking_text
            description: Booking text (often describing the type of booking, i.e. credit, debit, fee, etc.)
          - name: purpose
            description: Transaction description
          - name: balance
            description: Account balance at the time of the booking
          - name: balance_currency
            description: Currency unit for the balance column
          - name: amount
            description: Amount of the booking
          - name: amount_currency
            description: Currency unit for the amount column
          - name: inserted_at
            description: Timestamp when the record was inserted

      - name: categories
        description: List of categories available to categorize transactions
        columns:
          - name: category_id
            description: Category ID
            tests:
              - unique
              - not_null
          - name: name
            description: Category Name
          - name: created_at
            description: Timestamp when the category was created

      - name: transaction_categories
        description: Table with the categories of each transaction
        columns:
          - name: transaction_id
            description: Transaction ID
          - name: categoriy_id
            description: Category ID
          - name: created_at
            description: Timestamp when the transaction was categorized for the first time
          - name: updated_at
            description: Timestamp when the transaction was last categorized
