name: PyTest
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
      # Mobile folder working directory.
        working-directory: app

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            app:
              - 'app/**'

      # Setup Python (faster than using Python container)
      - name: Setup Python
        if: steps.filter.outputs.app == 'true'
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
      - id: cache-pipenv
        if: steps.filter.outputs.Mobile == 'true'
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        if: |
          steps.cache-pipenv.outputs.cache-hit != 'true' &&
          steps.filter.outputs.Mobile == 'true'
        run: |
          pipenv install --deploy --dev
      - name: Run test suite
        if: steps.filter.outputs.Mobile == 'true'
        run: |
          pipenv run test -v