name: Publish API image
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  test_api:
    name: Publish API image
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            api:
              - 'api/**'

      - name: Log in to Docker Hub
        if: steps.filter.outputs.api == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ secrets.DOCKER_REPOSITORY }}
      
      - name: Build and push Docker image
        if: steps.filter.outputs.api == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./api
          file: ./api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_REPOSITORY }}/${{ secrets.DOCKER_USERNAME }}/my-finances-api:latest
