name: Test dbt App
on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  test_frontend:
    name: Test dbt
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dbt

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            dbt:
              - 'dbt/**'

      - name: Log in to Docker Hub
        if: steps.filter.outputs.dbt == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ secrets.DOCKER_REPOSITORY }}
      
      - name: Build and push Docker image
        if: steps.filter.outputs.dbt == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./dbt
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_REPOSITORY }}/${{ secrets.DOCKER_USERNAME }}/my-finances-dbt:test
          target: test

      - name: Run Test image
        if: steps.filter.outputs.dbt == 'true'
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ secrets.DOCKER_REPOSITORY }}/${{ secrets.DOCKER_USERNAME }}/my-finances-dbt:test
