name: Test Frontend App
on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  test_frontend:
    name: Test Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            frontend:
              - 'frontend/**'

      - name: Log in to Docker Hub
        if: steps.filter.outputs.frontend == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ secrets.DOCKER_REPOSITORY }}
      
      - name: Build and push Docker image
        if: steps.filter.outputs.frontend == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_REPOSITORY }}/${{ secrets.DOCKER_USERNAME }}/my-finances-frontend:test
          target: test

      - name: Run Test image
        if: steps.filter.outputs.frontend == 'true'
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ secrets.DOCKER_REPOSITORY }}/${{ secrets.DOCKER_USERNAME }}/my-finances-frontend:test
          options: |
            -e POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
            -e POSTGRES_USER=${{ secrets.POSTGRES_USER }}
            -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            -e POSTGRES_DB=${{ secrets.POSTGRES_DB }}
