name: Test API App
on: push

jobs:
  test_api:
    name: Test API
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            api:
              - 'api/**'

      - name: Log in to Docker Hub
        if: steps.filter.outputs.api == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        if: steps.filter.outputs.api == 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: PabloPardoGarcia/my-finances-api:test
          target: test

      - name: Run Test image
        if: steps.filter.outputs.api == 'true'
        uses: docker/run-action@v3
        with:
          image: my-finances-api:test
          options: |
            -e POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
            -e POSTGRES_USER=${{ secrets.POSTGRES_USER }}
            -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            -e POSTGRES_DB=${{ secrets.POSTGRES_DB }}
